# Generated by Django 5.2.1 on 2025-05-17 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('completed', 'Completada')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('author', models.CharField(max_length=255, verbose_name='Autor')),
                ('publication_date', models.DateField(verbose_name='Fecha de publicación')),
                ('resource_type', models.CharField(choices=[('publication', 'Publicación'), ('magazine', 'Revista'), ('book', 'Libro'), ('article', 'Artículo'), ('other', 'Otro')], default='publication', max_length=20, verbose_name='Tipo de recurso')),
                ('pdf_file', models.FileField(help_text='Sube un archivo PDF (máximo 20MB)', upload_to='resources/', verbose_name='Archivo PDF')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN')),
                ('publisher', models.CharField(blank=True, max_length=255, null=True, verbose_name='Editorial')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de páginas')),
                ('language', models.CharField(blank=True, max_length=50, null=True, verbose_name='Idioma')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Número de descargas')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Número de vistas')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'ordering': ['-publication_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_professional', models.BooleanField(default=False, verbose_name='¿Es profesional?')),
                ('specialization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Especialización')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de teléfono')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biografía')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Foto de perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
