# Generated by Django 5.2.1 on 2025-05-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_appointment_date_end_appointment_date_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date_end',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_start',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='None', max_length=255, verbose_name='Categoría'),
        ),
    ]
