# Generated by Django 5.2.1 on 2025-05-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_date_end_event_date_remove_event_date_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='resource_type',
            new_name='rType',
        ),
    ]
